import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <div>
          <p><Link href={"/"}>To Home</Link></p>
          <p><Link href={"/login"}>To Login</Link></p>
          <p><Link href={"/map"}>To Map</Link></p>
          <p><Link href={"/users"}>To Users</Link></p>
        </div>

        {children}
      </body>
    </html>
  );
}
